ISSUE_CATALOG = {
    "missing_readme": {
        "title": "README missing",
        "why_it_matters": "The repository is hard to understand quickly and loses strong portfolio value.",
        "recommendation": "Add a README with project overview, installation, usage, and technical structure.",
        "severity": "high",
    },
    "readme_too_short": {
        "title": "README too short",
        "why_it_matters": "The project context is too weak to explain value, scope, or usage.",
        "recommendation": "Expand the README with purpose, setup, usage, and project structure.",
        "severity": "medium",
    },
    "missing_project_description": {
        "title": "Project description missing in README",
        "why_it_matters": "Readers may not understand what the repository actually does.",
        "recommendation": "Add a clear overview section explaining the project goal and scope.",
        "severity": "medium",
    },
    "missing_installation_instructions": {
        "title": "Installation instructions missing",
        "why_it_matters": "The project is harder to reproduce and use.",
        "recommendation": "Add installation or setup steps to the README.",
        "severity": "high",
    },
    "missing_usage_instructions": {
        "title": "Usage instructions missing",
        "why_it_matters": "The repository is difficult to run or evaluate.",
        "recommendation": "Document how to run the project and provide example commands.",
        "severity": "high",
    },
    "missing_project_structure_explanation": {
        "title": "Project structure not explained",
        "why_it_matters": "The repository layout is less understandable for maintainers and recruiters.",
        "recommendation": "Add a short section describing key folders and modules.",
        "severity": "low",
    },
    "missing_demo_or_examples": {
        "title": "No demo or examples detected",
        "why_it_matters": "The project is less convincing and harder to evaluate quickly.",
        "recommendation": "Add screenshots, example outputs, or a demo section.",
        "severity": "low",
    },
    "missing_roadmap_or_limitations": {
        "title": "No roadmap or limitations section detected",
        "why_it_matters": "The project maturity and future direction are unclear.",
        "recommendation": "Add roadmap, known limitations, or next steps.",
        "severity": "low",
    },
    "flat_project_structure": {
        "title": "Flat project structure",
        "why_it_matters": "Too many root-level files usually indicate weak organization.",
        "recommendation": "Group code, tests, docs, and assets into dedicated directories.",
        "severity": "high",
    },
    "missing_main_code_directory": {
        "title": "Main code directory missing",
        "why_it_matters": "The codebase appears less structured and harder to scale.",
        "recommendation": "Move main source code into a dedicated folder such as src/, app/, or lib/.",
        "severity": "high",
    },
    "missing_tests_directory": {
        "title": "Tests directory missing",
        "why_it_matters": "Test organization is unclear or absent.",
        "recommendation": "Add a dedicated tests/ directory.",
        "severity": "medium",
    },
    "missing_supporting_directories": {
        "title": "Supporting directories missing",
        "why_it_matters": "The repository may lack separation for docs, assets, data, or scripts.",
        "recommendation": "Add relevant directories such as docs/, assets/, data/, or scripts/ when needed.",
        "severity": "low",
    },
    "inconsistent_naming": {
        "title": "Inconsistent or vague naming",
        "why_it_matters": "Weak file naming hurts readability and maintainability.",
        "recommendation": "Rename vague files and enforce consistent naming conventions.",
        "severity": "medium",
    },
    "versioned_junk_files": {
        "title": "Versioned junk files detected",
        "why_it_matters": "Temporary or generated files make the repository noisier and less professional.",
        "recommendation": "Remove junk files and strengthen .gitignore rules.",
        "severity": "medium",
    },
    "missing_dependency_manifest": {
        "title": "Dependency manifest missing",
        "why_it_matters": "Dependencies are not formalized, which harms reproducibility.",
        "recommendation": "Add an appropriate dependency manifest such as pyproject.toml or package.json.",
        "severity": "high",
    },
    "missing_gitignore": {
        "title": ".gitignore missing",
        "why_it_matters": "Generated files are more likely to be committed accidentally.",
        "recommendation": "Add a proper .gitignore file for the project stack.",
        "severity": "high",
    },
    "missing_license": {
        "title": "License missing",
        "why_it_matters": "The repository usage rights are unclear.",
        "recommendation": "Add a LICENSE file.",
        "severity": "low",
    },
    "missing_tooling_configuration": {
        "title": "Tooling configuration missing",
        "why_it_matters": "Formatting, linting, or testing standards are less explicit.",
        "recommendation": "Add configuration for core tools such as pytest, ruff, eslint, or tsconfig.",
        "severity": "medium",
    },
    "missing_env_example": {
        "title": "Environment example missing",
        "why_it_matters": "Projects using configuration or secrets are harder to reproduce safely.",
        "recommendation": "Add a .env.example or equivalent configuration template.",
        "severity": "medium",
    },
    "missing_tests": {
        "title": "No tests detected",
        "why_it_matters": "The project appears fragile and less maintainable.",
        "recommendation": "Add a basic test suite covering core logic and critical flows.",
        "severity": "high",
    },
    "insufficient_test_coverage_apparent": {
        "title": "Test presence appears weak",
        "why_it_matters": "A very small number of tests often indicates fragile coverage.",
        "recommendation": "Increase the breadth of tests for critical paths.",
        "severity": "medium",
    },
    "missing_test_framework_configuration": {
        "title": "Test framework not clearly configured",
        "why_it_matters": "The testing strategy is less explicit and reproducible.",
        "recommendation": "Declare and configure the testing framework clearly.",
        "severity": "medium",
    },
    "missing_ci_for_tests": {
        "title": "CI for tests missing",
        "why_it_matters": "Quality checks are not automatically enforced.",
        "recommendation": "Add CI workflows to run tests automatically.",
        "severity": "low",
    },
    "oversized_files": {
        "title": "Oversized files detected",
        "why_it_matters": "Very large files often indicate weak modularity and harder maintenance.",
        "recommendation": "Split large files into smaller focused modules.",
        "severity": "high",
    },
    "monolithic_structure": {
        "title": "Monolithic structure detected",
        "why_it_matters": "Too much logic concentrated in too few files hurts scalability.",
        "recommendation": "Separate the codebase into clearer modules and responsibilities.",
        "severity": "high",
    },
    "vague_file_names": {
        "title": "Vague file names detected",
        "why_it_matters": "Generic names reduce readability and professionalism.",
        "recommendation": "Rename files to reflect their specific responsibility.",
        "severity": "medium",
    },
    "poor_separation_of_concerns": {
        "title": "Poor separation of concerns",
        "why_it_matters": "Responsibilities appear mixed, which makes future changes harder.",
        "recommendation": "Split logic into dedicated layers or modules.",
        "severity": "high",
    },
    "missing_technical_documentation": {
        "title": "Technical documentation missing",
        "why_it_matters": "Architecture and maintainability decisions are harder to understand.",
        "recommendation": "Add technical docs such as architecture notes or contribution guidelines.",
        "severity": "low",
    },
    "missing_repository_description": {
        "title": "Repository description missing",
        "why_it_matters": "The repo is less understandable at first glance on GitHub.",
        "recommendation": "Add a concise GitHub repository description.",
        "severity": "low",
    },
    "stale_repository": {
        "title": "Repository appears stale",
        "why_it_matters": "An old untouched repository may look abandoned.",
        "recommendation": "Update the project, refresh documentation, or mark it as archived if appropriate.",
        "severity": "low",
    },
    "empty_or_nearly_empty_repo": {
        "title": "Repository is empty or nearly empty",
        "why_it_matters": "The project does not currently demonstrate meaningful value.",
        "recommendation": "Add actual implementation, documentation, or archive/remove the repo.",
        "severity": "high",
    },
    "missing_demo_artifacts": {
        "title": "Demo artifacts missing",
        "why_it_matters": "The project is harder to evaluate quickly as a portfolio item.",
        "recommendation": "Add screenshots, sample outputs, or a live demo link.",
        "severity": "low",
    },
    "project_promise_not_supported_by_contents": {
        "title": "Project promise is weakly supported by repository contents",
        "why_it_matters": "The repo may look incomplete or under-delivered compared to its description.",
        "recommendation": "Align README, structure, and code to match the stated project scope.",
        "severity": "medium",
    },
    "low_portfolio_clarity": {
        "title": "Low portfolio clarity",
        "why_it_matters": "The project is not immediately understandable to a recruiter or reviewer.",
        "recommendation": "Clarify the purpose, impact, and usage of the project.",
        "severity": "medium",
    },
    "low_technical_credibility": {
        "title": "Low technical credibility",
        "why_it_matters": "The repository lacks signals of engineering maturity.",
        "recommendation": "Improve structure, documentation, testing, and tooling signals.",
        "severity": "medium",
    },
    "hard_to_present_in_interview": {
        "title": "Hard to present in interview",
        "why_it_matters": "The project lacks quick evidence of output, value, or usability.",
        "recommendation": "Add examples, demo material, and clearer execution instructions.",
        "severity": "low",
    },
}